name: CI

on:
  pull_request:

  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6.x]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Test
      run: bundle exec rspec
